---
test:
  name: helloword
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 5
  rounds:
  - label: open-liner
    txDuration:
    - 5
    rateControl:
    - type: linear-rate
      opts:
        startingTps: 25
        finishingTps: 75
    arguments:
      money: 10000
    callback: benchmark/fisco-bcos/helloworld/open.js
  - label: query
    txDuration:
    - 15
    rateControl:
    - type: linear-rate
      opts:
        startingTps: 25
        finishingTps: 75
    callback: benchmark/fisco-bcos/helloworld/query.js
monitor:
  type:
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
