---
test:
  name: helloword
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 2
  rounds:
  - label: create account
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      money: 10000
    callback: benchmark/fisco-bcos/smallbank/open.js
  - label: transfer money
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      money: 200
    callback: benchmark/fisco-bcos/smallbank/transfer.js
  - label: query balance
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    callback: benchmark/fisco-bcos/smallbank/query.js
monitor:
  type:
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
